apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-arbeidsgiver
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  accessPolicy:
    outbound:
      rules:
        - application: narmesteleder
  gcp:
    sqlInstances:
      - name: sykmeldinger-arbeidsgiver-instance
        type: POSTGRES_12
        diskSize: 10
        databases:
          - name: sykmeldinger-arbeidsgiver
            envVarPrefix: NAIS_DATABASE
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 2048m
      memory: 1Gi
    requests:
      cpu: 1024m
      memory: 768Mi
  vault:
    enabled: false
  ingresses:
    - "https://sykmeldinger-arbeidsgiver.dev.intern.nav.no"
    - "https://sykmeldinger-arbeidsgiver.dev.nav.no"
  webproxy: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  envFrom:
    - secret: sykmeldinger-arbeidsgiver-secrets
    - configmap: loginservice-idporten
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: NARMESTELEDER_URL
      value: https://narmesteleder.dev.nav.no
    - name: ALLOWED_ORIGIN
      value: tjenester-q1.nav.no,www-gcp.dev.nav.no,sykmeldinger-arbeidsgiver.dev.nav.no
