apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-arbeidsgiver
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  accessPolicy:
    outbound:
      rules:
        - application: narmesteleder
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: sykmeldinger-arbeidsgiver-instance
        type: POSTGRES_12
        diskSize: 10
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        databases:
          - name: sykmeldinger-arbeidsgiver
            envVarPrefix: NAIS_DATABASE
  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 60
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: false
  ingresses:
    - "https://sykmeldinger-arbeidsgiver.nav.no"
    - "https://sykmeldinger-arbeidsgiver.intern.nav.no"
  webproxy: true
  envFrom:
    - secret: sykmeldinger-arbeidsgiver-secrets
    - configmap: loginservice-idporten
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: NARMESTELEDER_URL
      value: https://narmesteleder.nav.no
    - name: ALLOWED_ORIGIN
      value: tjenester.nav.no,www.nav.no
