apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-arbeidsgiver
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  accessPolicy:
    outbound:
      rules:
        - application: narmesteleder
      external:
        - host: pdl-api.prod-fss-pub.nais.io
    inbound:
      rules:
        - application: oppfolgingsplan-frontend
          namespace: team-esyfo
          cluster: prod-gcp
        - application: dialogmote-frontend
          namespace: team-esyfo
          cluster: prod-gcp
        - application: syfobrukertilgang
          namespace: team-esyfo
          cluster: prod-gcp
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: sykmeldinger-arbeidsgiver-instance
        type: POSTGRES_12
        diskSize: 10
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        databases:
          - name: sykmeldinger-arbeidsgiver
            envVarPrefix: NAIS_DATABASE
  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 60
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
  leaderElection: true
  envFrom:
    - secret: sykmeldinger-arbeidsgiver-secrets
  env:
    - name: ALLOWED_ORIGIN
      value: tjenester.nav.no,www.nav.no
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
