apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-arbeidsgiver
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: sykmeldinger-arbeidsgiver-instance
        type: POSTGRES_12
        diskSize: 10
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        databases:
          - name: sykmeldinger-arbeidsgiver
            envVarPrefix: NAIS_DATABASE
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 60
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: false
  ingresses:
    - "https://sykmeldinger-arbeidsgiver.intern.nav.no"
  webproxy: true
